import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "vi" | "en" | "kr" | "jp" | "th";

interface Translations {
    [key: string]: {
        [lang in Language]: string;
    };
}

const translations: Translations = {
    settings: {
        vi: "Cài đặt",
        en: "Settings",
        kr: "설정",
        jp: "設定",
        th: "การตั้งค่า",
    },
    profile: {
        vi: "Cá nhân",
        en: "Profile",
        kr: "프로필",
        jp: "プロフィール",
        th: "프로필",
    },
    account: {
        vi: "Tài khoản",
        en: "Account",
        kr: "계정",
        jp: "アカウント",
        th: "บัญชี",
    },
    personalInfo: {
        vi: "Thông tin cá nhân",
        en: "Personal Information",
        kr: "개인 정보",
        jp: "個人情報",
        th: "ข้อมูลส่วนตัว",
    },
    changePassword: {
        vi: "Đổi mật khẩu",
        en: "Change Password",
        kr: "비밀번호 변경",
        jp: "パスワード変更",
        th: "เปลี่ยนรหัสผ่าน",
    },
    notifications: {
        vi: "Thông báo",
        en: "Notifications",
        kr: "알림",
        jp: "通知",
        th: "การแจ้งเตือน",
    },
    language: {
        vi: "Ngôn ngữ",
        en: "Language",
        kr: "언어",
        jp: "言語",
        th: "ภาษา",
    },
    logout: {
        vi: "Đăng xuất",
        en: "Logout",
        kr: "로그아웃",
        jp: "ログアウト",
        th: "ออกจากระบบ",
    },
    editProfile: {
        vi: "Chỉnh sửa hồ sơ",
        en: "Edit Profile",
        kr: "프로필 편집",
        jp: "プロフィールを編集",
        th: "แก้ไขโปรไฟล์",
    },
    notUpdated: {
        vi: "Chưa cập nhật",
        en: "Not updated",
        kr: "업데이트되지 않음",
        jp: "未更新",
        th: "ยังไม่ได้อัปเดต",
    },
    skip: {
        vi: "Bỏ qua",
        en: "Skip",
        kr: "건너뛰기",
        jp: "スキップ",
        th: "ข้าม",
    },
    next: {
        vi: "Tiếp theo",
        en: "Next",
        kr: "다음",
        jp: "次へ",
        th: "ถัดไป",
    },
    start: {
        vi: "Bắt đầu",
        en: "Start",
        kr: "시작",
        jp: "スタート",
        th: "เริ่ม",
    },
    finish: {
        vi: "Hoàn tất",
        en: "Finish",
        kr: "완성",
        jp: "完了",
        th: "เสร็จสิ้น",
    },
    ready: {
        vi: "Tôi đã sẵn sàng",
        en: "I'm ready",
        kr: "준비됐어",
        jp: "準備完了",
        th: "ฉันพร้อมแล้ว",
    },
    welcomeOnboarding: {
        vi: "Trước khi bắt đầu, hãy để tớ làm quen với bạn nhé!",
        en: "Before we start, let me get to know you!",
        kr: "시작하기 전에, 당신에 대해 알려주세요!",
        jp: "始める前に、あなたのことを教えてください！",
        th: "ก่อนที่เราจะเริ่ม ให้ฉันได้รู้จักคุณหน่อย!",
    },
    enterNickname: {
        vi: "Nhập biệt danh của bạn",
        en: "Enter your nickname",
        kr: "닉네임을 입력하세요",
        jp: "ニックネームを入力してください",
        th: "กรอกชื่อเล่นของคุณ",
    },
    nicknameHint: {
        vi: "Biệt danh phải dài từ 5-15 ký tự và chỉ có thể bao gồm chữ cái, số, dấu gạch dưới (_) và dấu chấm (.).",
        en: "Nickname must be 5-15 characters long and can only include letters, numbers, underscores (_), and periods (.).",
        kr: "닉네임은 5-15자 이내여야 하며 문자, 숫자, 밑줄(_) 및 마침표(.)만 포함할 수 있습니다.",
        jp: "ニックネームは5〜15文字で、文字、数字、アンダースコア（_）、およびピリオド（.）のみを含めることができます。",
        th: "ชื่อเล่นต้องมีความยาว 5-15 ตัวอักษร และสามารถรวมตัวอักษร ตัวเลข เครื่องหมายขีดล่าง (_) และจุด (.) เท่านั้น",
    },
    referralCode: {
        vi: "Mã giới thiệu",
        en: "Referral code",
        kr: "추천 코드",
        jp: "紹介コード",
        th: "รหัสแนะนำ",
    },
    enterReferral: {
        vi: "Nhập mã giới thiệu (nếu có)",
        en: "Enter referral code (if any)",
        kr: "추천 코드 입력 (있는 경우)",
        jp: "紹介コードを入力（ある場合）",
        th: "กรอกรหัสแนะนำ (ถ้ามี)",
    },
    genderQuestion: {
        vi: "Giới tính của bạn là gì?",
        en: "What is your gender?",
        kr: "성별이 무엇입니까?",
        jp: "性別は何ですか？",
        th: "เพศของคุณคืออะไร?",
    },
    locationQuestion: {
        vi: "Bạn sống ở đâu?",
        en: "Where do you live?",
        kr: "어디에 사세요?",
        jp: "どこに住んでいますか？",
        th: "คุณอาศัยอยู่ที่ไหน?",
    },
    lifestyleQuestion: {
        vi: "Vui lòng chọn phong cách sống và loại hình công việc chính của bạn.",
        en: "Please select your lifestyle and primary work type.",
        kr: "라이프스타일과 주요 업무 유형을 선택하세요.",
        jp: "ライフスタイルと主な職業の種類を選択してください。",
        th: "โปรดเลือกไลฟ์สไตล์และประเภทงานหลักของคุณ",
    },
    hairColorQuestion: {
        vi: "Màu tóc của bạn là gì?",
        en: "What is your hair color?",
        kr: "머리카락 색깔이 무엇입니까?",
        jp: "髪の色は何ですか？",
        th: "สีผมของคุณคืออะไร?",
    },
    eyeColorQuestion: {
        vi: "Màu mắt của bạn là gì?",
        en: "What is your eye color?",
        kr: "눈 색깔이 무엇입니까?",
        jp: "目の色は何ですか？",
        th: "สีตาของคุณคืออะไร?",
    },
    bodyShapeQuestion: {
        vi: "Dáng người của bạn là gì?",
        en: "What is your body shape?",
        kr: "체형이 무엇입니까?",
        jp: "体型は何ですか？",
        th: "รูปร่างของคุณคืออะไร?",
    },
    colorPaletteQuestion: {
        vi: "Tông màu nào hợp với bạn nhất?",
        en: "Which color palette suits you best?",
        kr: "어떤 색상 팔레트가 가장 잘 어울리나요?",
        jp: "どのカラーパレットが一番似合いますか？",
        th: "จานสีไหนที่คุณคิดว่าเหมาะกับคุณที่สุด?",
    },
    fashionStyleQuestion: {
        vi: "Chọn phong cách bạn yêu thích",
        en: "Choose your favorite fashion styles",
        kr: "좋아하는 패션 스타일을 선택하세요",
        jp: "お気に入りのファッションスタイルを選択してください",
        th: "เลือกสไตล์แฟชั่นที่คุณชื่นชอบ",
    },
    other: {
        vi: "Khác",
        en: "Other",
        kr: "기타",
        jp: "その他",
        th: "อื่นๆ",
    },
    notSure: {
        vi: "Tôi không chắc",
        en: "I'm not sure",
        kr: "잘 모르겠어요",
        jp: "わからない",
        th: "ฉันไม่แน่ใจ",
    },
    female: {
        vi: "Nữ",
        en: "Female",
        kr: "여성",
        jp: "女性",
        th: "ผู้หญิง",
    },
    male: {
        vi: "Nam",
        en: "Male",
        kr: "남성",
        jp: "男性",
        th: "ผู้ชาย",
    },
    nonbinary: {
        vi: "Phi nhị giới",
        en: "Non-binary",
        kr: "논바이너리",
        jp: "ノンバイナリー",
        th: "นอน-ไบนารี",
    },
    private: {
        vi: "Không muốn tiết lộ",
        en: "Prefer not to say",
        kr: "말하고 싶지 않음",
        jp: "回答しない",
        th: "ไม่ต้องการระบุ",
    },
    studentHS: {
        vi: "Học sinh cấp 2/cấp 3",
        en: "Middle/High School Student",
        kr: "중/고등학생",
        jp: "中高生",
        th: "นักเรียนมัธยม",
    },
    studentUni: {
        vi: "Sinh viên đại học",
        en: "University Student",
        kr: "대학생",
        jp: "大学生",
        th: "นักศึกษา",
    },
    officeCasual: {
        vi: "Nhân viên mặc trang phục casual",
        en: "Office Worker (Casual)",
        kr: "사무직 (캐주얼)",
        jp: "オフィスワーカー (カジュアル)",
        th: "พนักงานออฟฟิศ (แคชชวล)",
    },
    officeFormal: {
        vi: "Nhân viên mặc trang phục trang trọng",
        en: "Office Worker (Formal)",
        kr: "사무직 (정장)",
        jp: "オフィスワーカー (フォーマル)",
        th: "พนักงานออฟฟิศ (ฟอร์มัล)",
    },
    uniform: {
        vi: "Nhân viên mặc đồng phục",
        en: "Worker in Uniform",
        kr: "제복 착용자",
        jp: "制服勤務",
        th: "พนักงานในเครื่องแบบ",
    },
    homemaker: {
        vi: "Nội trợ",
        en: "Homemaker",
        kr: "주부",
        jp: "主婦・主夫",
        th: "พ่อบ้าน/แม่บ้าน",
    },
    blonde: {
        vi: "Tóc vàng",
        en: "Blonde",
        kr: "금발",
        jp: "金髪",
        th: "ผมบลอนด์",
    },
    brownHair: {
        vi: "Tóc nâu",
        en: "Brown hair",
        kr: "갈색 머리",
        jp: "茶髪",
        th: "ผมสีน้ำตาล",
    },
    blackHair: {
        vi: "Tóc nâu sẫm/Đen",
        en: "Dark brown/Black hair",
        kr: "검정색 머리",
        jp: "黒髪",
        th: "ผมสีดำ",
    },
    redHair: {
        vi: "Tóc đỏ",
        en: "Red hair",
        kr: "빨간색 머리",
        jp: "赤髪",
        th: "ผมสีแดง",
    },
    grayHair: {
        vi: "Tóc xám/Bạc",
        en: "Gray/Silver hair",
        kr: "회색/은색 머리",
        jp: "グレー/シルバーヘア",
        th: "ผมสีเทา/เงิน",
    },
    brownEye: {
        vi: "Nâu",
        en: "Brown",
        kr: "갈색",
        jp: "ブラウン",
        th: "สีน้ำตาล",
    },
    blackEye: {
        vi: "Đen",
        en: "Black",
        kr: "검정",
        jp: "ブラック",
        th: "สีดำ",
    },
    blueEye: {
        vi: "Xanh dương",
        en: "Blue",
        kr: "파란색",
        jp: "ブルー",
        th: "สีฟ้า",
    },
    hazelEye: {
        vi: "Nâu hạt dẻ",
        en: "Hazel",
        kr: "헤이즐",
        jp: "ヘーゼル",
        th: "สีเฮเซล",
    },
    greenEye: {
        vi: "Xanh lá",
        en: "Green",
        kr: "초록색",
        jp: "グリーン",
        th: "สีเขียว",
    },
    grayEye: {
        vi: "Xám",
        en: "Gray",
        kr: "회색",
        jp: "グレー",
        th: "สีเทา",
    },
    hourglass: {
        vi: "Đồng hồ cát",
        en: "Hourglass",
        kr: "모래시계형",
        jp: "砂時計型",
        th: "ทรงนาฬิกาทราย",
    },
    pear: {
        vi: "Tam giác",
        en: "Pear (Triangle)",
        kr: "배형 (삼각형)",
        jp: "洋ナシ型 (三角形)",
        th: "ทรงลูกแพร์",
    },
    invertedTriangle: {
        vi: "Tam giác ngược",
        en: "Inverted Triangle",
        kr: "역삼각형",
        jp: "逆三角形",
        th: "ทรงสามเหลี่ยมคว่ำ",
    },
    apple: {
        vi: "Dáng tròn",
        en: "Apple (Round)",
        kr: "사과형",
        jp: "リンゴ型",
        th: "ทรงแอปเปิ้ล",
    },
    rectangle: {
        vi: "Chữ nhật",
        en: "Rectangle",
        kr: "직사각형",
        jp: "長方形",
        th: "ทรงสี่เหลี่ยม",
    },
    warmBright: {
        vi: "Ấm áp · Tươi sáng",
        en: "Warm · Bright",
        kr: "따뜻하고 밝음",
        jp: "ウォーム・ブライト",
        th: "อบอุ่น · สดใส",
    },
    coolSoft: {
        vi: "Mát mẻ · Dịu dàng",
        en: "Cool · Soft",
        kr: "시원하고 부드러움",
        jp: "クール・ソフト",
        th: "เย็น · นุ่มนวล",
    },
    warmDeep: {
        vi: "Ấm áp · Sâu lắng",
        en: "Warm · Deep",
        kr: "따뜻하고 깊음",
        jp: "ウォーム・ディープ",
        th: "อบอุ่น · ลุ่มลึก",
    },
    darkMoody: {
        vi: "Tối · Cá tính",
        en: "Dark · Moody",
        kr: "어둡고 분위기 있음",
        jp: "ダーク・ムーディー",
        th: "มืด · มีมู้ด",
    },
    casual: {
        vi: "Thường ngày",
        en: "Casual",
        kr: "캐주얼",
        jp: "カジュアル",
        th: "แคชชวล",
    },
    minimal: {
        vi: "Tối giản",
        en: "Minimal",
        kr: "미니멀",
        jp: "ミニマル",
        th: "มินิมอล",
    },
    streetwear: {
        vi: "Streetwear",
        en: "Streetwear",
        kr: "스트리트웨어",
        jp: "ストリートウェア",
        th: "สตรีทแวร์",
    },
    athleisure: {
        vi: "Thể thao/Athleisure",
        en: "Athleisure",
        kr: "애슬레저",
        jp: "アスレジャー",
        th: "แอธเลเชอร์",
    },
    elegant: {
        vi: "Thanh lịch",
        en: "Elegant",
        kr: "엘레강트",
        jp: "エレガント",
        th: "เอเลแกนซ์",
    },
    vintage: {
        vi: "Vintage/Retro",
        en: "Vintage/Retro",
        kr: "빈티지/레트로",
        jp: "ヴィンテージ/レトロ",
        th: "วินเทจ/เรโทร",
    },
    readyMsg: {
        vi: "Hồ sơ đã sẵn sàng! Chào mừng bạn đến V-Closet 🎉",
        en: "Profile ready! Welcome to V-Closet 🎉",
        kr: "프로필 완료! V-Closet에 오신 것을 환영합니다 🎉",
        jp: "プロフィールの準備ができました！V-Closetへようこそ 🎉",
        th: "โปรไฟล์พร้อมแล้ว! ยินดีต้อนรับสู่ V-Closet 🎉",
    },
    edit: {
        vi: "Chỉnh sửa",
        en: "Edit",
        kr: "편집",
        jp: "編集",
        th: "แก้ไข",
    },
    save: {
        vi: "Lưu",
        en: "Save",
        kr: "저장",
        jp: "保存",
        th: "บันทึก",
    },
    community: {
        vi: "Cộng đồng",
        en: "Community",
        kr: "커뮤니티",
        jp: "コミュニティ",
        th: "ชุมชน",
    },
    wardrobe: {
        vi: "Tủ đồ",
        en: "Wardrobe",
        kr: "옷장",
        jp: "ワードローブ",
        th: "ตู้เสื้อผ้า",
    },
    outfit: {
        vi: "Phối đồ",
        en: "Outfit",
        kr: "아웃핏",
        jp: "アウトフィット",
        th: "ชุด",
    },
    camera: {
        vi: "Máy ảnh",
        en: "Camera",
        kr: "카메라",
        jp: "カメラ",
        th: "กล้อง",
    },
    following: {
        vi: "Đang theo dõi",
        en: "Following",
        kr: "팔로잉",
        jp: "フォロー中",
        th: "กำลังติดตาม",
    },
    followers: {
        vi: "Người theo dõi",
        en: "Followers",
        kr: "팔로워",
        jp: "フォロワー",
        th: "ผู้ติดตาม",
    },
    posts: {
        vi: "Bài viết",
        en: "Posts",
        kr: "게시물",
        jp: "投稿",
        th: "โพสต์",
    },
    votes: {
        vi: "Lượt bình chọn",
        en: "Votes",
        kr: "투표",
        jp: "投票",
        th: "โหวต",
    },
    shopee: {
        vi: "Mua trên Shopee",
        en: "Buy on Shopee",
        kr: "쇼피에서 구매",
        jp: "Shopeeで購入",
        th: "ซื้อบน Shopee",
    },
    personalStats: {
        vi: "Chỉ số cá nhân",
        en: "Personal Stats",
        kr: "개인 통계",
        jp: "個人統計",
        th: "สถิติส่วนตัว",
    },
    wardrobeHistory: {
        vi: "Lịch sử tủ đồ",
        en: "Wardrobe History",
        kr: "옷장 기록",
        jp: "ワードローブ履歴",
        th: "ประวัติตู้เสื้อผ้า",
    },
    help: {
        vi: "Trợ giúp",
        en: "Help",
        kr: "도움말",
        jp: "ヘルプ",
        th: "ช่วยเหลือ",
    },
    nickname: {
        vi: "Biệt danh",
        en: "Nickname",
        kr: "닉네임",
        jp: "ニックネーム",
        th: "ชื่อเล่น",
    },
    gender: {
        vi: "Giới tính",
        en: "Gender",
        kr: "성별",
        jp: "性別",
        th: "เพศ",
    },
    country: {
        vi: "Quốc gia",
        en: "Country",
        kr: "국가",
        jp: "国",
        th: "ประเทศ",
    },
    vietnam: {
        vi: "Việt Nam",
        en: "Vietnam",
        kr: "베트남",
        jp: "ベトナム",
        th: "เวียดนาม",
    },
    usa: {
        vi: "Hoa Kỳ",
        en: "United States",
        kr: "미국",
        jp: "アメリカ",
        th: "สหรัฐอเมริกา",
    },
    japan: {
        vi: "Nhật Bản",
        en: "Japan",
        kr: "일본",
        jp: "日本",
        th: "ญี่ปุ่น",
    },
    korea: {
        vi: "Hàn Quốc",
        en: "South Korea",
        kr: "대한민국",
        jp: "韓国",
        th: "เกาหลีใต้",
    },
    thailand: {
        vi: "Thái Lan",
        en: "Thailand",
        kr: "태국",
        jp: "タイ",
        th: "ไทย",
    },
    singapore: {
        vi: "Singapore",
        en: "Singapore",
        kr: "싱가포르",
        jp: "シンガポール",
        th: "สิงคโปร์",
    },

    saveChanges: {
        vi: "Lưu thay đổi",
        en: "Save Changes",
        kr: "변경 사항 저장",
        jp: "変更を保存",
        th: "บันทึกการเปลี่ยนแปลง",
    },
    resetPassword: {
        vi: "Cập nhật mật khẩu",
        en: "Update Password",
        kr: "비밀번호 업데이트",
        jp: "パスワードを更新",
        th: "อัปเดตรหัสผ่าน",
    },
    oldPassword: {
        vi: "Mật khẩu cũ",
        en: "Old Password",
        kr: "이전 비밀번호",
        jp: "古いパスワード",
        th: "รหัสผ่านเดิม",
    },
    newPassword: {
        vi: "Mật khẩu mới",
        en: "New Password",
        kr: "새 비밀번호",
        jp: "新しいパスワード",
        th: "รหัสผ่านใหม่",
    },
    confirmPassword: {
        vi: "Xác nhận mật khẩu mới",
        en: "Confirm New Password",
        kr: "새 비밀번호 확인",
        jp: "新しいパスワードを隠す",
        th: "ยืนยันรหัสผ่านใหม่",
    },
    forgotPassword: {
        vi: "Bạn quên mật khẩu?",
        en: "Forgot password?",
        kr: "비밀번호를 잊으셨나요?",
        jp: "パスワードを忘れた場合",
        th: "ลืมรหัสผ่าน?",
    },
    login: {
        vi: "Đăng nhập",
        en: "Login",
        kr: "로그인",
        jp: "ログイン",
        th: "เข้าสู่ระบบ",
    },
    register: {
        vi: "Đăng ký",
        en: "Register",
        kr: "회원가입",
        jp: "新規登録",
        th: "ลงทะเบียน",
    },
    welcomeBack: {
        vi: "Chào mừng trở lại",
        en: "Welcome Back",
        kr: "다시 오신 것을 환영합니다",
        jp: "おかえりなさい",
        th: "ยินดีต้อนรับกลับมา",
    },
    loginSub: {
        vi: "Truy cập tủ đồ kỹ thuật số và thử đồ ảo ngay.",
        en: "Access your digital wardrobe and virtual try-on.",
        kr: "디지털 옷장에 액세스하고 가상 피팅을 시작하세요.",
        jp: "デジタルワードローブにアクセスして、仮想試着を体験しましょう。",
        th: "เข้าถึงตู้เสื้อผ้าดิจิทัลและการลองชุดเสมือนจริง",
    },
    emailOrUser: {
        vi: "Email hoặc Tên đăng nhập",
        en: "Email or Username",
        kr: "이메일 또는 사용자 이름",
        jp: "メールアドレスまたはユーザー名",
        th: "อีเมลหรือชื่อผู้ใช้",
    },
    password: {
        vi: "Mật khẩu",
        en: "Password",
        kr: "비밀번호",
        jp: "パスワード",
        th: "รหัสผ่าน",
    },
    enterEmail: {
        vi: "Nhập email của bạn",
        en: "Enter your email",
        kr: "이메일을 입력하세요",
        jp: "メールアドレスを入力してください",
        th: "กรอกอีเมลของคุณ",
    },
    loginToCloset: {
        vi: "Đăng nhập vào Tủ đồ",
        en: "Login to Your Closet",
        kr: "내 옷장에 로그인",
        jp: "クローゼットにログイン",
        th: "เข้าสู่ระบบตู้เสื้อผ้าของคุณ",
    },
    orContinueWith: {
        vi: "Hoặc tiếp tục với",
        en: "Or continue with",
        kr: "또는 다음으로 계속",
        jp: "または以下で続行",
        th: "หรือดำเนินการต่อด้วย",
    },
    dontHaveAccount: {
        vi: "Chưa có tài khoản?",
        en: "Don't have an account?",
        kr: "계정이 없으신가요?",
        jp: "アカウントをお持ちでない場合",
        th: "ยังไม่มีบัญชีใช่ไหม?",
    },
    createAccount: {
        vi: "Tạo tài khoản",
        en: "Create Account",
        kr: "계정 만들기",
        jp: "アカウント作成",
        th: "สร้างบัญชี",
    },
    registerSub: {
        vi: "Tham gia V-Closet để bắt đầu xây dựng tủ đồ kỹ thuật số.",
        en: "Join V-Closet to start building your digital wardrobe.",
        kr: "V-Closet에 가입하여 디지털 옷장을 만들기 시작하세요.",
        jp: "V-Closetに参加して、デジタルワードローブを構築しましょう。",
        th: "เข้าร่วม V-Closet เพื่อเริ่มสร้างตู้เสื้อผ้าดิจิทัลของคุณ",
    },
    fullName: {
        vi: "Họ và tên",
        en: "Full Name",
        kr: "성명",
        jp: "氏名",
        th: "ชื่อ-นามสกุล",
    },
    enterFullName: {
        vi: "Nhập họ và tên của bạn",
        en: "Enter your full name",
        kr: "성명을 입력하세요",
        jp: "氏名を入力してください",
        th: "กรอกชื่อ-นามสกุลของคุณ",
    },
    emailAddress: {
        vi: "Địa chỉ Email",
        en: "Email Address",
        kr: "이메일 주소",
        jp: "メールアドレス",
        th: "ที่อยู่อีเมล",
    },
    createPassword: {
        vi: "Tạo mật khẩu",
        en: "Create a password",
        kr: "비밀번호 만들기",
        jp: "パスワードを作成",
        th: "สร้างรหัสผ่าน",
    },
    alreadyHaveAccount: {
        vi: "Đã có tài khoản?",
        en: "Already have an account?",
        kr: "이미 계정이 있으신가요?",
        jp: "既にアカウントをお持ちの場合",
        th: "มีบัญชีอยู่แล้วใช่ไหม?",
    },
    subscription: {
        vi: "Gói dịch vụ",
        en: "Subscription",
        kr: "구독",
        jp: "サブスクリプション",
        th: "การสมัครสมาชิก",
    },
    payment: {
        vi: "Thanh toán",
        en: "Payment",
        kr: "결제",
        jp: "支払い",
        th: "การจ่ายเงิน",
    },
    freePlan: {
        vi: "Gói FREE",
        en: "FREE Plan",
        kr: "무료 플랜",
        jp: "フリープラン",
        th: "แผนฟรี",
    },
    monthlyPlan: {
        vi: "Gói MONTHLY",
        en: "MONTHLY Plan",
        kr: "월간 플랜",
        jp: "月間プラン",
        th: "แผนรายเดือน",
    },
    yearlyPlan: {
        vi: "Gói YEARLY",
        en: "YEARLY Plan",
        kr: "연간 플랜",
        jp: "年間プラン",
        th: "แผนรายปี",
    },
    selectPlan: {
        vi: "Chọn gói",
        en: "Select Plan",
        kr: "플랜 선택",
        jp: "プランを選択",
        th: "เลือกแผน",
    },
    momo: {
        vi: "Ví MoMo",
        en: "MoMo E-wallet",
        kr: "모모 전자지갑",
        jp: "MoMo電子マネー",
        th: "วอลเล็ต MoMo",
    },
    vnpay: {
        vi: "VNPay",
        en: "VNPay",
        kr: "VNPay",
        jp: "VNPay",
        th: "VNPay",
    },
    bankTransfer: {
        vi: "Chuyển khoản Ngân hàng",
        en: "Bank Transfer",
        kr: "은행 송금",
        jp: "銀行振込",
        th: "โอนผ่านธนาคาร",
    },
};

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguageState] = useState<Language>("vi");

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
    };

    const t = (key: string) => {
        if (!translations[key]) return key;
        return translations[key][language] || translations[key]["en"];
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
